/* LANGUAGE MODAL */
export const OPEN_LANGUAGE_MODAL = "OPEN_LANGUAGE_MODAL";
export const CLOSE_LANGUAGE_MODAL = "CLOSE_LANGUAGE_MODAL";

/* SIDE MENU */
export const OPEN_SIDE_MENU = "OPEN_SIDE_MENU";
export const CLOSE_SIDE_MENU = "CLOSE_SIDE_MENU";

/* ADMIN LOGIN */
export const ADMIN_LOGIN_START = "ADMIN_LOGIN_START";
export const ADMIN_LOGIN_ERROR = "ADMIN_LOGIN_ERROR";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";

/* ADMIN ABOUT */
export const ADMIN_ABOUT_START = "ADMIN_ABOUT_START";
export const ADMIN_ABOUT_ERROR = "ADMIN_ABOUT_ERROR";
export const ADMIN_ABOUT_SUCCESS = "ADMIN_ABOUT_SUCCESS";

/* GET ADMIN ABOUT */
export const GET_ADMIN_ABOUT_DATA_START = "GET_ADMIN_ABOUT_DATA_START";
export const GET_ADMIN_ABOUT_DATA_SUCCESS = "GET_ADMIN_ABOUT_DATA_SUCCESS";
export const GET_ADMIN_ABOUT_DATA_ERROR = "GET_ADMIN_ABOUT_DATA_ERROR";

/* UPLOAD ABOUT IMAGE */
export const UPLOAD_ABOUT_IMAGE_START = "UPLOAD_ABOUT_IMAGE_START";
export const UPLOAD_ABOUT_IMAGE_SUCCESS = "UPLOAD_ABOUT_IMAGE_SUCCESS";
export const UPLOAD_ABOUT_IMAGE_ERROR = "UPLOAD_ABOUT_IMAGE_ERROR";

/* DELETE ABOUT IMAGE */
export const DELETE_ABOUT_IMAGE_START = "DELETE_ABOUT_IMAGE_START";
export const DELETE_ABOUT_IMAGE_SUCCESS = "DELETE_ABOUT_IMAGE_SUCCESS";
export const DELETE_ABOUT_IMAGE_ERROR = "DELETE_ABOUT_IMAGE_ERROR";