/* LANGUAGE MODAL */
export const OPEN_LANGUAGE_MODAL = "OPEN_LANGUAGE_MODAL";
export const CLOSE_LANGUAGE_MODAL = "CLOSE_LANGUAGE_MODAL";

/* SIDE MENU */
export const OPEN_SIDE_MENU = "OPEN_SIDE_MENU";
export const CLOSE_SIDE_MENU = "CLOSE_SIDE_MENU";